services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Cyve\LogViewerBundle\:
        resource: '../../*'
        exclude: '../../{Controller,DependencyInjection,Tests,CyveLogViewerBundle.php}'

    Cyve\LogViewerBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
